version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    hostname: db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database_name
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app

  nginx_nest:
    image: nginx:latest
    container_name: nginx_nest
    ports:
      - '8081:80'
    volumes:
      - ./nginx/nest.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nest1
      - nest2
      - nest3
    networks:
      - app

  nest1:
    container_name: nest1
    build:
      context: ./nest
      dockerfile: Dockerfile
    hostname: nest1
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app
      
  nest2:
    container_name: nest2
    build:
      context: ./nest
      dockerfile: Dockerfile
    hostname: nest2
    ports:
      - '4001:4000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app

  nest3:
    container_name: nest3
    build:
      context: ./nest
      dockerfile: Dockerfile
    hostname: nest3
    ports:
      - '4002:4000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  app:
    driver: bridge